### ISSUE TITLE
quiz results showing error

### ISSUE THREAD

**Issue by nishkalprakash** [mask-tech/MASK#54]
Hi,

Found error on attempting static quiz 

got this error on the console:
```
[
  {
    points: 0,
    _id: new ObjectId("63d256b5d5ad02d4834cd0f7"),
    '2022-03-13': { score: 1, time: 1670007950023 }
  }
]
[
  {
    points: 0,
    _id: new ObjectId("63d256bad5ad02d4834cd101"),
    '2022-03-13': { score: 1, time: 1670007950023 }
  }
]
D:\Downloads\DarKSkuLL\MASK\node_modules\mongoose\lib\document.js:3097
de:internal/process/task_queues:77:11) {
  errors: {    'quizData.0.quizId': ValidatorError: Path `quizId` is required.
        at validate (D:\Downloads\DarKSkuLL\MASK\node_modules\mongoose\lib\schematype.js:1346:13)
        at SchemaType.doValidate (D:\Downloads\DarKSkuLL\MASK\node_modules\mongoose\lib\schematype.js:1330:7)        at D:\Downloads\DarKSkuLL\MASK\node_modules\mongoose\lib\document.js:2877:18        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {      properties: {
        validator: [Function (anonymous)],        message: 'Path `quizId` is required.',        type: 'required',
        path: 'quizId',        value: undefined      },
      kind: 'required',
      path: 'quizId',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'UserQuizData validation failed'
}
```

**Comment by nishkalprakash** [comment]
issue in dev branch

**Comment by nishkalprakash** [comment]
steps to reproduce

- attempt any static quiz
- click on results on the "`http://localhost:6969/quizzes`" 
- server crashes

**Comment by Goose-Of-War** [comment]
Test database stuff, don't worry about it. The issue was fixed in prod already
